package hero

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
)

const TypeBytesBuffer = "*bytes.Buffer"
const TypeIOWriter = "io.Writer"

var formatMap = map[string]string{
	String:    "%s",
	Interface: "fmt.Sprintf(\"%%v\", %s)",
	Int:       "hero.FormatInt(int64(%s), buffer)",
	Uint:      "hero.FormatUint(uint64(%s), buffer)",
	Float:     "hero.FormatFloat(float64(%s), buffer)",
	Bool:      "hero.FormatBool(%s, buffer)",
}

func writeToFile(path string, buffer *bytes.Buffer) {
	err := ioutil.WriteFile(path, buffer.Bytes(), os.ModePerm)
	if err != nil {
		panic(err)
	}
}

func genAbsPath(path string) string {
	if !filepath.IsAbs(path) {
		path, _ = filepath.Abs(path)
	}
	return path
}

func checkError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

// parseDefinition parses the function definition.
func parseDefinition(definition string) (*ast.FuncDecl, error) {
	src := fmt.Sprintf("package hero\n%s", definition)

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "", src, parser.AllErrors)
	if err != nil {
		return nil, err
	}

	funcDecl, ok := file.Decls[0].(*ast.FuncDecl)
	if !ok {
		return nil, errors.New("Definition is not function type")
	}
	return funcDecl, nil
}

// parseParams parses parameters in the function definition.
func parseParams(funcDecl *ast.FuncDecl) (name, t string, err error) {
	params := funcDecl.Type.Params.List
	if len(params) == 0 {
		err = errors.New(
			"Definition parameters should not be empty",
		)
		return
	}

	lastParam := params[len(params)-1]

	selectorExpr, ok := lastParam.Type.(*ast.SelectorExpr)
	if !ok {
		err = errors.New(
			"The last parameter should be *bytes.Buffer or io.Writer type",
		)
		return
	}

	t = fmt.Sprintf("%s.%s", selectorExpr.X, selectorExpr.Sel)

	if t != TypeBytesBuffer && t != TypeIOWriter {
		err = errors.New(
			"The last parameter should be *bytes.Buffer or io.Writer type",
		)
		return
	}

	if n := len(lastParam.Names); n > 0 {
		name = lastParam.Names[n-1].Name
	}

	return
}

// parseResults parses the returned results in the function definition.
func parseResults(funcDecl *ast.FuncDecl) (types []string) {
	results := funcDecl.Type.Results.List
	for _, field := range results {
		types = append(types, fmt.Sprintf("%s", field.Type))
	}
	return
}

// gen generates code to buffer.
func gen(n *node, buffer *bytes.Buffer, bufName string) {
	for _, child := range n.children {
		switch child.t {
		case TypeCode:
			buffer.Write(child.chunk.Bytes())
		case TypeHTML:
			buffer.WriteString(fmt.Sprintf(
				"%s.WriteString(`%s`)",
				bufName,
				child.chunk.String(),
			))
		case TypeRawValue, TypeEscapedValue:
			var format string

			switch child.subtype {
			case Int, Uint, Float, Bool, String, Interface:
				format = formatMap[child.subtype]
				if child.subtype != String &&
					child.subtype != Interface {
					goto WriteFormat
				}
			case Bytes:
				if child.t == TypeRawValue {
					format = fmt.Sprintf("%s.Write(%%s)", bufName)
					goto WriteFormat
				}
				format = "*(*string)(unsafe.Pointer(&(%s)))"
			default:
				log.Fatal("unknown value type: " + child.subtype)
			}

			if child.t == TypeEscapedValue {
				format = fmt.Sprintf(
					"hero.EscapeHTML(%s, %s)", format, bufName,
				)
			} else {
				format = fmt.Sprintf(
					"%s.WriteString(%s)", bufName, format,
				)
			}

		WriteFormat:
			buffer.WriteString(fmt.Sprintf(format, child.chunk.String()))
		case TypeBlock, TypeInclude:
			gen(child, buffer, bufName)
		default:
			continue
		}

		buffer.WriteByte(BreakLine)
	}
}

// Generate generates go code from source to test. pkgName represents the
// package name of the generated code.
func Generate(source, dest, pkgName string) {
	defer cleanGlobal()

	source, dest = genAbsPath(source), genAbsPath(dest)

	stat, err := os.Stat(source)
	checkError(err)

	fmt.Println("Parsing...")
	if stat.IsDir() {
		parseDir(source)
	} else {
		source, file := filepath.Split(source)
		parseFile(source, file)
	}

	stat, err = os.Stat(dest)
	if os.IsNotExist(err) {
		if err = os.MkdirAll(dest, os.ModePerm); err != nil {
			log.Fatal(err)
		}
	} else if !stat.IsDir() {
		log.Fatal(dest + " is not dir")
	} else if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Generating...")

	var wg sync.WaitGroup
	for path, n := range parsedNodes {
		wg.Add(1)

		fileName := filepath.Join(dest, fmt.Sprintf(
			"%s.go",
			strings.Join(strings.Split(path[len(source)+1:], "/"), "_"),
		))

		go func(n *node, source, fileName string) {
			defer wg.Done()

			buffer := bytes.NewBufferString(`
				// Code generated by hero.
			`)
			buffer.WriteString(fmt.Sprintf("// source: %s", source))
			buffer.WriteString(`
				// DO NOT EDIT!
			`)
			buffer.WriteString(fmt.Sprintf("package %s\n", pkgName))
			buffer.WriteString(`
				import "html"
				import "unsafe"

				import "github.com/shiyanhui/hero"
			`)

			imports := n.childrenByType(TypeImport)
			for _, item := range imports {
				buffer.Write(item.chunk.Bytes())
			}

			definitions := n.childrenByType(TypeDefinition)
			if len(definitions) == 0 {
				writeToFile(fileName, buffer)
				return
			}

			definition := definitions[0].chunk.String()

			funcDecl, err := parseDefinition(definition)
			checkError(err)

			buffer.WriteString(definition)
			buffer.WriteString(`{
			`)

			paramName, paramType, err := parseParams(funcDecl)
			checkError(err)

			if paramType == TypeIOWriter {
				bufName := "_buffer"

				buffer.WriteString(
					fmt.Sprintf(
						"%s := hero.GetBuffer()\ndefer hero.PutBuffer(%s)\n",
						bufName, bufName,
					),
				)
				gen(n, buffer, bufName)

				results, ret := parseResults(funcDecl), ""
				if reflect.DeepEqual(results, []string{"int", "error"}) {
					ret = "return"
				}

				buffer.WriteString(
					fmt.Sprintf(
						"%s %s.Write(%s.Bytes())\n",
						ret, paramName, bufName,
					),
				)
			} else {
				gen(n, buffer, paramName)
			}

			buffer.WriteString(`
			}`)

			writeToFile(fileName, buffer)
		}(n, path, fileName)
	}
	wg.Wait()

	fmt.Println("Executing goimports...")
	execCommand("goimports -w " + dest)

	fmt.Println("Executing go vet...")
	execCommand("go tool vet -v " + dest)
}
