// Code generated by hero.
// source: /Users/Lime/Documents/workspace/GoProject/src/github.com/shiyanhui/hero/examples/app/template/userlistwriter.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/shiyanhui/hero"
)

func UserListToWriter(userList []string, w io.Writer) {
	buffer := hero.GetBuffer()
	defer hero.PutBuffer(buffer)
	buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        `)
	for _, user := range userList {
		buffer.WriteString(`
        <ul>
            `)
		buffer.WriteString(`<li>
    `)
		hero.EscapeHTML(user, buffer)
		buffer.WriteString(`
</li>
`)

		buffer.WriteString(`
        </ul>
    `)
	}

	buffer.WriteString(`
    </body>
</html>
`)
	w.Write(buffer.Bytes())
}
